/************************************
|                                   | 
|   Javier Izquierdo Vera           |
|   Juan Carlos Gallardo Morales    |
|   2ºBII                           |
|                                   |
|   NapakalakiGame - PDOO           |
|                                   |
************************************/

package GUI;

import NapakalakiGame.Cultist;
import NapakalakiGame.CultistPlayer;
import NapakalakiGame.Player;
import javax.swing.ImageIcon;

public class CultistView extends javax.swing.JPanel {
    
    
    private CultistInfo ci;
    private Cultist cultistModel;

    public CultistView() {
        initComponents();
    }
    
    
    public void setCultist(Cultist cultistCard){
        
        cultistModel = cultistCard;
        String name = cultistCard.getName();
        ImageIcon icon;
        
        // Default
        icon = new ImageIcon(getClass().getResource("/GUI/img/sectarios/sect01m.png"));
        
        if (name == "Sectario 2")
             icon = new ImageIcon(getClass().getResource("/GUI/img/sectarios/sect02m.png"));
        else if (name == "Sectario 3")
             icon = new ImageIcon(getClass().getResource("/GUI/img/sectarios/sect03m.png"));
        else if (name == "Sectario 4")
             icon = new ImageIcon(getClass().getResource("/GUI/img/sectarios/sect04m.png"));
        else if (name == "Sectario 5")
             icon = new ImageIcon(getClass().getResource("/GUI/img/sectarios/sect05m.png"));
        else if (name == "Sectario 6")
             icon = new ImageIcon(getClass().getResource("/GUI/img/sectarios/sect06m.png"));
        
        img.setIcon(icon);
        ci = new CultistInfo(cultistModel);
        repaint();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        img = new javax.swing.JLabel();

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/img/sectarios/sect01m.png"))); // NOI18N
        img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgMouseClicked
        ci.setVisible(true);
    }//GEN-LAST:event_imgMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img;
    // End of variables declaration//GEN-END:variables
}
