/************************************
|                                   | 
|   Javier Izquierdo Vera           |
|   Juan Carlos Gallardo Morales    |
|   2ºBII                           |
|                                   |
|   NapakalakiGame - PDOO           |
|                                   |
************************************/

package GUI;

import NapakalakiGame.Cultist;
import javax.swing.ImageIcon;

public class CultistInfo extends javax.swing.JFrame {

    private Cultist cultistModel;

    public CultistInfo(Cultist cardCultist) {
        initComponents();
        cultistModel = cardCultist;
        setImage(cultistModel.getName());
    }
    
    private void setImage(String name){
        ImageIcon icon;
        
        // Default
        icon = new ImageIcon(getClass().getResource("/GUI/img/sectarios/sect01.png"));
        
        if (name == "Sectario 2")
             icon = new ImageIcon(getClass().getResource("/GUI/img/sectarios/sect02.png"));
        else if (name == "Sectario 3")
             icon = new ImageIcon(getClass().getResource("/GUI/img/sectarios/sect03.png"));
        else if (name == "Sectario 4")
             icon = new ImageIcon(getClass().getResource("/GUI/img/sectarios/sect04.png"));
        else if (name == "Sectario 5")
             icon = new ImageIcon(getClass().getResource("/GUI/img/sectarios/sect05.png"));
        else if (name == "Sectario 6")
             icon = new ImageIcon(getClass().getResource("/GUI/img/sectarios/sect06.png"));
        
        img.setIcon(icon);
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        img = new javax.swing.JLabel();

        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/img/treasures/default.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(img)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(img)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
         setVisible(false);
    }//GEN-LAST:event_formWindowLostFocus

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel img;
    // End of variables declaration//GEN-END:variables
}
